on:
  push:
    branches:
      - main

name: Build and test in Docker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: docker build . -t go-test
    - name: Test
      run: docker run go-test go test ./...