on:
  push:
    branches:
      - main

name: Build and test in Docker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    - name: 'Build'
      uses: docker/build-push-action@v2
      with:
        registry: ghcr.io
        username: "ijimiji"
        password: ${{ secrets.PAT }}
        repository: ijimiji/go-coding-challenge-jr
        tags: latest
    - name: Test
      run: docker run latest go test ./...